name: linting, testing, building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }} environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production build
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts
      - name: linting scss
        run: npm run lint:scss
      - name: prettify code
        run: npm run prettier:check
      - name: unit testing
        run: npm run test:unit